spring.application.name=erp-api

# Conexão com o PostgreSQL na Nuvem (Render)
spring.datasource.url=jdbc:postgresql://dpg-dae30dad0e5s73euvu80-a.oregon-postgres.render.com:5432/lf_db_qiso
spring.datasource.username=lf_db_qiso_user
spring.datasource.password=40Hl2RZ6FDAABsVuSdJMVYhwJsBAX5ru
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true